# Generated by Django 3.2 on 2021-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('log_time', models.DateTimeField()),
                ('method', models.CharField(max_length=7)),
                ('endpoint', models.TextField()),
                ('protocol', models.CharField(max_length=25)),
                ('response_code', models.IntegerField()),
                ('respose_size', models.IntegerField()),
                ('referer', models.URLField(null=True)),
                ('user_agent', models.TextField()),
            ],
        ),
    ]
